import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./applications.scss";
import "../../public/bootstrap-icons.min.css";
import LanguageProvider from "@app/lib/LanguageProvider/LanguageProvider";
import React from "react";



const inter = Inter({subsets: ["latin"]});



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({children, }: Readonly<{children: React.ReactNode;}>) {


    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/*<script src="/bootstrap.bundle.min.js"*/}
                {/*        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"*/}
                {/*        crossOrigin="anonymous" async></script>*/}
            </head>
            <body className={"d-flex flex-column min-vh-100"}>
                <LanguageProvider>
                    {children}
                </LanguageProvider>
            </body>
        </html>
    );
}
